/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2018-09-27 12:31:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" class=\" js no-touch\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>STUDY|Plataforma de Estudos</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600|Raleway:600,300|Josefin+Slab:400,700,600italic,600,400italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/slick-team-slider.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!--Menu principal -->\r\n");
      out.write("  <div class=\"main-navigation navbar-fixed-top\">\r\n");
      out.write("    <nav class=\"navbar navbar-default\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"img/portfolio/imglogo.png\"style=\"width:105px;\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li class=\"active\"><a href=\"#banner\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#service\">Especificacões</a></li>\r\n");
      out.write("            <li><a href=\"#portfolio\">Disciplinas</a></li>\r\n");
      out.write("            <li><a href=\"#contact\">Cadastre-se</a></li>\r\n");
      out.write("            <li><a href=\".footer_social\">Contato</a></li>\r\n");
      out.write("            <li><a href=\"indexLogin.jsp\">Login</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!--BANNER PRINCIPAL -->\r\n");
      out.write("  <div id=\"banner\" class=\"section-padding\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"jumbotron\">\r\n");
      out.write("          <h1 class=\"small\">Bem-vindo ao <span class=\"bold\">STUDY[bot]</span></h1>\r\n");
      out.write("          <p class=\"big\">Tudo o que você precisa pra ir bem nos seus estudos.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--BANNER END-->\r\n");
      out.write("\r\n");
      out.write("  <!--TELA RESERVADA PARA O CHATBOT -->\r\n");
      out.write("  <div class=\"cta-1\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row text-center white\">\r\n");
      out.write("        <h1 class=\"cta-title\">Diga olá para o STUDY[bot]</h1>\r\n");
      out.write("        <p class=\"cta-sub-title\"><a data-toggle=\"modal\" data-target=\"#modalChat\">Clique aqui para tirar sua dúvida</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--FINAL DA TELA RESERVADA PARA O CHAT BOT -->\r\n");
      out.write("\r\n");
      out.write("  <!--TELA COM AS DISCIPLINAS -->\r\n");
      out.write("  <div id=\"service\" class=\"section-padding\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"page-title text-center\">\r\n");
      out.write("          <h1>Nossas Disciplinas</h1>\r\n");
      out.write("          <p> </p>\r\n");
      out.write("          <hr class=\"pg-titl-bdr-btm\"></hr>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"service-box\">\r\n");
      out.write("            <div class=\"service-icon\"><i class=\"fa fa-desktop\"></i></div>\r\n");
      out.write("            <div class=\"service-text\">\r\n");
      out.write("              <h3>Lógica de programação</h3>\r\n");
      out.write("              <p> Lógica de Programação é a técnica de desenvolver algoritmos (sequências lógicas) para atingir determinados objetivos dentro de certas regras baseadas na Lógica matemática e em outras teorias.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"service-box\">\r\n");
      out.write("            <div class=\"service-icon\"><i class=\"fa fa-television\"></i></div>\r\n");
      out.write("            <div class=\"service-text\">\r\n");
      out.write("              <h3>Banco de dados </h3>\r\n");
      out.write("              <p>Bancos de dados ou bases de dados são um conjunto de arquivos relacionados entre si com registros sobre pessoas, lugares ou coisas. São coleções organizadas de dados que se relacionam de forma a criar algum sentido e dar mais eficiência durante uma pesquisa ou estudo.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"service-box\">\r\n");
      out.write("            <div class=\"service-icon\"><i class=\"fa fa-laptop\"></i></div>\r\n");
      out.write("            <div class=\"service-text\">\r\n");
      out.write("              <h3>Linguagens de programação </h3>\r\n");
      out.write("              <p>Diversas linguagens de programação surgiram desde então. Entre estas incluem-se C#, VB.NET, Java, Object Pascal, Objective-C, PHP, Python, SuperCollider, linguagem D e Ruby.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <div class=\"service-box\">\r\n");
      out.write("            <div class=\"service-icon\"><i class=\"fa fa-globe\"></i></div>\r\n");
      out.write("            <div class=\"service-text\">\r\n");
      out.write("              <h3>Programação WEB</h3>\r\n");
      out.write("              <p> Desenvolvimento web é o termo utilizado para descrever o desenvolvimento de sites, na Internet ou numa intranet. Este é o profissional que trabalha desenvolvendo websites, podendo ser um Web Designer (Desenvolvedor do Layout), ou Web Developer(Desenvolvedor de sistemas). O desenvolvimento refere-se a um processo de construção e testes do software especifico para a web, com a finalidade de se obter um conjunto de programas, que satisfazem as funções pretendidas, quer em termos de usabilidade dos usuários ou compatibilidade com outros programas existentes. O desenvolvimento web pode variar desde simples páginas estáticas a aplicações ricas, comércios eletrônicos ou redes sociais.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--FIM DA TELA RESERVADA PARA AS DISCIPLINAS-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div id=\"portfolio\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"page-title text-center\">\r\n");
      out.write("        <h1>Conheça melhor os nossos cursos</h1>\r\n");
      out.write("        <hr class=\"pg-titl-bdr-btm\"></hr>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\" id=\"portfolio-wrapper\">\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("          <a href=\"cursos.jsp\">\r\n");
      out.write("            <img src=\"img/portfolio/imgJava.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("              <h4>Java</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 portfolio-item filter-web\">\r\n");
      out.write("          <a href=\"cursos.jsp\">\r\n");
      out.write("            <img src=\"img/portfolio/dba.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("              <h4>Banco de dados</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 portfolio-item filter-app\">\r\n");
      out.write("          <a href=\"cursos.jsp\">\r\n");
      out.write("            <img src=\"img/portfolio/web3.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("              <h4>Web</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 portfolio-item filter-card\">\r\n");
      out.write("          <a href=\"cursos.jsp\">\r\n");
      out.write("            <img src=\"img/portfolio/tecnologia.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("              <h4>Lógica de programação</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!--começo contato / cadastro -->\r\n");
      out.write("  <div id=\"contact\" class=\"section-padding\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"page-title text-center\">\r\n");
      out.write("          <h1>Cadastre-se</h1>\r\n");
      out.write("          <p></p>\r\n");
      out.write("          <hr class=\"pg-titl-bdr-btm\"></hr>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"sendmessage\">sua menssagem foi enviada.Obrigado</div>\r\n");
      out.write("        <div id=\"errormessage\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-sec\">\r\n");
      out.write("          <form action=\"cadastraAluno\" method=\"post\" role=\"form\" class=\"contactForm\">\r\n");
      out.write("          \t <div class=\"col-md-4 form-group\">\r\n");
      out.write("          \t <select class=\"form-control\" id=\"descHistorico\" nome=\"descHistorico\">\r\n");
      out.write("          \t     <option>EXCELENTE</option>\r\n");
      out.write("    \t\t\t <option>BOM</option>\r\n");
      out.write("   \t\t\t\t <option>MEDIO</option>\r\n");
      out.write("  \t\t\t     <option>RUIM</option>\r\n");
      out.write("  \t\t\t  </select>\r\n");
      out.write("          \t </div>\r\n");
      out.write("          \t <div class=\"col-md-4 form-group\">\r\n");
      out.write("          \t <select class=\"form-control\" id=\"grauEscolaridade\" name=\"grauEscolaridade\" placeholder=\"escolha uma Escolaridade\" >\r\n");
      out.write("          \t     <option>SUPERIOR</option>\r\n");
      out.write("   \t\t\t\t <option>FUNDAMENTAL 2</option>\r\n");
      out.write("  \t\t\t     <option>FUNDAMENTAL 1</option>\r\n");
      out.write("  \t\t\t  </select>\r\n");
      out.write("          \t </div>\r\n");
      out.write("          \t <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"date\"  name=\"dataFormacao\" id=\"dataFormacao\" placeholder=\"Data de formação\"/>\r\n");
      out.write("              <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"text\"  class=\"form-control text-field-box\" name=\"nome\" id=\"nome\" placeholder=\"Seu nome\" data-rule=\"minlen:4\" data-msg=\"PorFavor coloque no minumo 4 caracteres\" />\r\n");
      out.write("              <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"text\"  class=\"form-control text-field-box\" name=\"apelido\" id=\"apelido\" placeholder=\"Seu apelido\" data-rule=\"minlen:4\" data-msg=\"PorFavor coloque no minumo 4 caracteres\" />\r\n");
      out.write("            <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("           <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"text\"  class=\"form-control text-field-box\" name=\"rg\" id=\"rg\" placeholder=\"Digite o rg\" data-rule=\"minlen:4\" data-msg=\"PorFavor coloque no minumo 4 caracteres\" />\r\n");
      out.write("            <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"text\"  class=\"form-control text-field-box\" name=\"cpf\" id=\"cpf\" placeholder=\"Digite o cpf\" data-rule=\"minlen:4\" data-msg=\"PorFavor coloque no minumo 4 caracteres\" />\r\n");
      out.write("            <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"date\" name=\"dataNascimento\" id=\"dataNascimento\" placeholder=\"Digite a data de nascimento\" />\r\n");
      out.write("            <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"email\" class=\"form-control text-field-box\" name=\"email\" id=\"email\" placeholder=\"Seu e-mail\" data-rule=\"email\"/>\r\n");
      out.write("              <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"text\" class=\"form-control text-field-box\" name=\"telefone\" id=\"telefone\" placeholder=\"Seu telefone\" data-rule=\"email\" data-msg=\"Por Favor valide seu e-mail\" />\r\n");
      out.write("              <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"password\" class=\"form-control text-field-box\" name=\"senha\" id=\"senha\" placeholder=\"Senha\" data-rule=\"email\" data-msg=\"Por Favor valide seu e-mail\" />\r\n");
      out.write("              <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 form-group\">\r\n");
      out.write("            <select class=\"form-control\" id=\"sexo\" nome=\"sexo\">\r\n");
      out.write("          \t     <option>MASCULINO</option>\r\n");
      out.write("    \t\t\t <option>FEMININO</option>\r\n");
      out.write("  \t\t\t </select>\r\n");
      out.write("          \t </div>\r\n");
      out.write("  \t\t    <div class=\"col-md-4 form-group\">\r\n");
      out.write("              <input type=\"text\" class=\"form-control text-field-box\" name=\"idade\" id=\"idade\" placeholder=\"Sua idade\" data-rule=\"email\" data-msg=\"Por Favor valide seu e-mail\" />\r\n");
      out.write("              <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("              <button class=\"button-medium\" id=\"contact-submit\" type=\"submit\" name=\"cadastrar\">Cadastre-se agora</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--fim contato / cadastro-->\r\n");
      out.write("\r\n");
      out.write("  <!--comeco footer-->\r\n");
      out.write("  <footer class=\"footer section-padding\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div style=\"visibility: visible; animation-name: zoomIn;\" class=\"col-sm-12 text-center wow zoomIn\">\r\n");
      out.write("          <h3>Siga-nos</h3>\r\n");
      out.write("          <div class=\"footer_social\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a class=\"f_facebook\" href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("              <li><a class=\"f_twitter\" href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("              <li><a class=\"f_google\" href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("              <li><a class=\"f_linkedin\" href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!--  modal para o chat  -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade bd-example-modal-sm\" id=\"modalChat\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write(" \t\t<div class=\"center\">\r\n");
      out.write("\t\t\t<h2>STUDY[BOT]</h2>\r\n");
      out.write("\t\t\t<div id=\"textchat\" class=\"pulse\"></div>\r\n");
      out.write("\t\t\t<form method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"question\" name=\"question\" class=\"field\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Escreva sua dúvida\" />\r\n");
      out.write("\t\t\t<button id=\"sendQuestion\">Enviar</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <!--  fim da modal/ chat  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!--fim footer-->\r\n");
      out.write("  <!-- rodapé direitos reservados -->\r\n");
      out.write("  <div class=\"footer-bottom\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div style=\"visibility: visible; animation-name: zoomIn;\" class=\"col-md-12 text-center wow zoomIn\">\r\n");
      out.write("        <div class=\"footer_copyright\">\r\n");
      out.write("          <p>©Study[BOT] todos os direitos reservados,2018.</p>\r\n");
      out.write("          <div class=\"credits\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/slick.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/custom.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/main.js\"></script>\r\n");
      out.write("  <!-- não funciona  <script src=\"contactform/contactform.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
