/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2018-09-25 11:11:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class indexLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" class=\" js no-touch\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>STUDY|Plataforma de Estudos</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600|Raleway:600,300|Josefin+Slab:400,700,600italic,600,400italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/slick-team-slider.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  <div class=\"main-navigation navbar-fixed-top\">\r\n");
      out.write("    <nav class=\"navbar navbar-default\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t    <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"img/portfolio/imglogo.png\"style=\"width:105px;\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("            <li class=\"active\"><a href=\"#banner\">Login</a></li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--começo contact-->\r\n");
      out.write("  <div id=\"login\" class=\"section-padding\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"page-title text-center\">\r\n");
      out.write("          <h1>Login </h1>\r\n");
      out.write("          <hr class=\"pg-titl-bdr-btm\"></hr>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"login\" method=\"post\" role=\"form\" class=\"contactForm\">\r\n");
      out.write("          <div class=\"form-sec\">\r\n");
      out.write("            <div class=\"col-md-6 form-group\">\r\n");
      out.write("              <input type=\"email\" class=\"form-control text-field-box\" name=\"email\" id=\"email\" placeholder=\"Seu e-mail\" data-rule=\"email\" data-msg=\"Por Favor valide seu e-mail\" />\r\n");
      out.write("              <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 form-group\">\r\n");
      out.write("              <input type=\"password\" class=\"form-control text-field-box\" name=\"senha\" id=\"subject\" placeholder=\"Senha\" data-rule=\"minlen:4\" data-msg=\"Por Favor coloque pelo menos 8 caracteres\" />\r\n");
      out.write("              <div class=\"validation\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"botoes\">\r\n");
      out.write("              <button class=\"button-medium\" id=\"contact-submit\" type=\"submit\" name=\"contact\">Entrar</button>&nbsp;\r\n");
      out.write("          <!--<button class=\"button-medium\" id=\"cadastrar\" type=\"submit\" name=\"cadastrar\"><a href=\"index.html#contact\"> Cadastrar</a></button> -->\r\n");
      out.write("             <a href=\"index.jsp#contact\" class=\"button-medium\" id=\"cadastrar\" type=\"submit\" name=\"cadastrar\"> Cadastrar</button></a> \r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--fim contact-->\r\n");
      out.write("  \r\n");
      out.write("<!--<form action=\"login\" method=\"post\">  APENAS CRIADO PARA TESTE\r\n");
      out.write("\r\n");
      out.write("\t\tUsuario: <input type=\"text\" name=\"email\">\r\n");
      out.write("\t\tSenha: <input type=\"text\" name=\"senha\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"login\">\r\n");
      out.write("\t\t\r\n");
      out.write("</form> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"/WEB-INF/paginas/meusCursos.jsp\"> teste página</a>\r\n");
      out.write("\r\n");
      out.write("  <!--comeco footer-->\r\n");
      out.write("  <footer class=\"footer section-padding\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div style=\"visibility: visible; animation-name: zoomIn;\" class=\"col-sm-12 text-center wow zoomIn\">\r\n");
      out.write("          <h3>Siga-nos</h3>\r\n");
      out.write("          <div class=\"footer_social\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a class=\"f_facebook\" href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("              <li><a class=\"f_twitter\" href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("              <li><a class=\"f_google\" href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("              <li><a class=\"f_linkedin\" href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!--fim footer-->\r\n");
      out.write("  <div class=\"footer-bottom\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div style=\"visibility: visible; animation-name: zoomIn;\" class=\"col-md-12 text-center wow zoomIn\">\r\n");
      out.write("        <div class=\"footer_copyright\" id=\"copy\">\r\n");
      out.write("          <p>©Study[BOT] todos os direitos reservados,2018.</p>\r\n");
      out.write("          <div class=\"credits\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/slick.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/custom.js\"></script>\r\n");
      out.write("  <!--   <script src=\"contactform/contactform.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
